services:
  network-tsdproxy:
    image: "almeidapaulopt/tsdproxy:1.4.7"
    container_name: "tsdproxy"
    restart: "unless-stopped"
    labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:${PORT_NETWORK_TSDPROXY}]"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/dkaser/unraid-plugins/main/tsdproxy.png"
    ports:
      - "${PORT_NETWORK_TSDPROXY}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/user/appdata/tower/tsdproxy:/data"
      - "/mnt/user/appdata/tower/tsdproxy-config:/config"