apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget
  namespace: budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      labels:
        app: budget
    spec:
      containers:
        - name: budget
          image: actualbudget/actual-server:latest
          ports:
            - containerPort: 5006
          env:
            - name: TZ
              value: "Europe/Copenhagen"
            - name: budget_PORT
              value: "5006"
          volumeMounts:
            - name: budget-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: budget-data
          persistentVolumeClaim:
            claimName: budget-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: budget
  namespace: budget
spec:
  selector:
    app: budget
  ports:
    - port: 5006
      targetPort: 5006
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budget
  namespace: budget
spec:
  defaultBackend:
    service:
      name: budget
      port:
        number: 5006
  ingressClassName: tailscale
  tls:
    - hosts:
        - budget