apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage
  - metallb
  - metallb-config
  - reflector
  - shared-secrets
  - traefik
  - tailscale
#  - cloudnative-pg