apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs-csi
  - storage
  - metallb
#  - metallb-config
  - reflector
  - sealed-secrets
#  - shared-secrets
  - traefik
  - tailscale
  - cloudnative-pg