apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-dash
  namespace: kitchen-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-dash
  template:
    metadata:
      labels:
        app: kitchen-dash
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: kitchen-dash
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: HOMEPAGE_ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TAILSCALE_HOMEPAGE_URL
          volumeMounts:
            - name: kitchen-dash-config
              mountPath: /app/config
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: kitchen-dash-config
          persistentVolumeClaim:
            claimName: kitchen-dash-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kitchen-dash
  namespace: kitchen-dash
spec:
  selector:
    app: kitchen-dash
  ports:
    - port: 3000
      targetPort: 3000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kitchen-dash
  namespace: kitchen-dash
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik-traefik
  rules:
    - host: kitchen-dash.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kitchen-dash
                port:
                  number: 3000