apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-nvme-client
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: tower.local
  share: /mnt/zfs_mirror/k8s-share
  subDir: "${pvc.metadata.name}"
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2
volumeBindingMode: Immediate
reclaimPolicy: Retain