services:
  stirlingpdf:
    image: stirlingtools/stirling-pdf:2.1.3
    container_name: stirlingpdf
    restart: "always"
    labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:78080]"
      tsdproxy.enable: "true"
      tsdproxy.name: "stirlingpdf"
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: "78080"
    environment:
      - TZ=Europe/Copenhagen
    ports:
      - "78080:8080"
