apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres
  - vaultwarden
  - stirlingpdf
  - mealie
  - budget
  - librespeed
  - karakeep
  - homepage
  - teslamate