apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate
  namespace: teslamate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: teslamate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: teslamate
    spec:
      containers:
        - name: teslamate
          image: teslamate/teslamate:2.1.1
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          env:
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TESLAMATE_ENCRYPTION_KEY
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_USER
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_PASS
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_DB_TESLAMATE
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_SHARED_INTERNAL_HOST
            - name: MQTT_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQTT_HOST
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQTT_USERNAME
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQTT_PASSWORD
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: teslamate-config
                  key: PORT
          volumeMounts:
            - name: import
              mountPath: /opt/app/import
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: import
          persistentVolumeClaim:
            claimName: teslamate-import
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        fsGroup: 10000