apiVersion: apps/v1
kind: Deployment
metadata:
  name: abrp
  namespace: teslamate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: abrp
  template:
    metadata:
      labels:
        app.kubernetes.io/component: abrp
    spec:
      containers:
        - name: abrp
          image: fetzu/teslamate-abrp:3.3.0
          env:
            - name: MQTT_SERVER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQTT_HOST
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQTT_USERNAME
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQTT_PASSWORD
            - name: USER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TESLAMATE_ABRP_KEY
            - name: CAR_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: teslamate-config
                  key: TESLAMATE_ABRP_CAR_NUMBER
            - name: CAR_MODEL
              valueFrom:
                configMapKeyRef:
                  name: teslamate-config
                  key: TESLAMATE_ABRP_CAR_MODEL
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        fsGroup: 10000