apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teslamate
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment-teslamate.yaml
  - deployment-grafana.yaml
  - deployment-abrp.yaml
  - service-teslamate.yaml
  - service-grafana.yaml
  - ingress.yaml
configMapGenerator:
  - name: teslamate-config
    literals:
      - PORT=4000
      - TESLAMATE_ABRP_CAR_NUMBER=1
      - TESLAMATE_ABRP_CAR_MODEL=mycar:21:other:other

commonLabels:
  app.kubernetes.io/name: teslamate
  app.kubernetes.io/part-of: teslamate