services:
  budget:
    image: actualbudget/actual-server:26.2.0
    container_name: budget
    restart: "always"
    labels:
      "net.unraid.docker.managed": "dockerman"
      "net.unraid.docker.webui": "http://[IP]:[PORT:5006]"
      "net.unraid.docker.icon": "https://github.com/actualbudget/actual/raw/master/packages/desktop-electron/icons/icon.png"
      tsdproxy.enable: "true"
      tsdproxy.name: "budget"
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: "5006"
    environment:
      - TZ=Europe/Copenhagen
      - budget_PORT=5006
    ports:
      - "5006:5006"
    volumes:
      - "${PATH_APPDATA_UNRAID}/budget:/data:rw"
