services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: "always"
    labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:5050]"
      net.unraid.docker.icon: "https://www.pgadmin.org/static/img/pgadmin4-logo.png"
    environment:
      - TZ=Europe/Copenhagen
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - "${PATH_APPDATA_UNRAID}/pgadmin4:/var/lib/pgadmin:rw"
