apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-superuser-secret.yaml
  - backup-pv.yaml
  - postgres-cluster.yaml
  - scheduled-backup.yaml
  - pgadmin.yaml
